# Generated by Django 4.2.7 on 2023-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroInforme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inspeccion', models.CharField(max_length=100, verbose_name='inspeccion')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tomado_por', models.CharField(max_length=100, verbose_name='tomado por')),
            ],
        ),
    ]
