# Generated by Django 4.2.7 on 2023-11-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosINREG', '0002_informetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='informeTest',
        ),
        migrations.RemoveField(
            model_name='numeroinforme',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='numeroinforme',
            name='inspeccion',
        ),
        migrations.RemoveField(
            model_name='numeroinforme',
            name='tomado_por',
        ),
    ]
