# Generated by Django 4.2.7 on 2023-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosINREG', '0003_delete_informetest_remove_numeroinforme_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroinforme',
            name='fecha',
            field=models.CharField(default=232, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroinforme',
            name='inspeccion_efectuada',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroinforme',
            name='numero_informe',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroinforme',
            name='tanque',
            field=models.CharField(default=212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroinforme',
            name='tipo',
            field=models.CharField(default=21212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroinforme',
            name='tomado_por',
            field=models.CharField(default=21212, max_length=100),
            preserve_default=False,
        ),
    ]
