# Generated by Django 4.2.7 on 2023-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosINREG', '0004_numeroinforme_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroIncr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_informe', models.CharField(max_length=100)),
            ],
        ),
    ]
