# Generated by Django 4.2.7 on 2023-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosINREG', '0005_numeroincr'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroincr',
            name='fecha',
            field=models.CharField(default=121, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroincr',
            name='inspeccion_efectuada',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroincr',
            name='tanque',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroincr',
            name='tipo',
            field=models.CharField(default=21212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroincr',
            name='tomado_por',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
    ]
