# Generated by Django 4.2.7 on 2023-12-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosINREG', '0006_numeroincr_fecha_numeroincr_inspeccion_efectuada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadGenerar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_informe', models.CharField(max_length=100)),
            ],
        ),
    ]
